spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: mardoner
        password: bhq70719179
        driver-class-name: com.mysql.jdbc.Driver
logging:
    level:
        com.mardoner.mall.admin.mapper: DEBUG
server:
    port: 8081
mybatis-plus:
    mapper-locations:
        - classpath*:/sqlMap/*.xml

